apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse

resources:
  - ../base
  - chk-keeper.yaml
  - keeper-pdb.yaml
  - ch-pdb-s01.yaml
  - ch-pdb-s02.yaml
  - ch-pdb-s03.yaml

patchesStrategicMerge:
  - chi-server-ipfix.yaml
